name: generator

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3
      - name: hd
        uses: linuxsuren/http-downloader@master
        with:
          tool: hd
      - name: run command
        run: |
          sudo cp /home/runner/work/_temp/_github_home/hd /usr/bin
          hd fetch
          hd version
          
          hd i k9s
          k9s version
