name: generator

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3
      - name: Update readme
        uses: linuxsuren/yaml-readme@57517a7b538828e1005866f096c792d052215760
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'items/*.yaml'
          username: linuxsuren-bot
          org: linuxsuren-bot
          repo: test
          tool: hd
      - name: hd
        uses: linuxsuren/http-downloader@master
        with:
          tool: k9s
      - name: run command
        run: |
          hd version
          k9s version
